<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Account</name>
   <tag></tag>
   <elementGuidId>8f9ce2aa-069f-4869-b5f1-9f92fbc095b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-site-wrapper']/div/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[alt=&quot;Account&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;My Account&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c5430b8-f39b-4f30-aa52-dc4c5d08f08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.borsheims.com/customer-account</value>
      <webElementGuid>9c3b144e-5784-4d32-ad56-e344c4e6ed72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>5323d523-b19c-4725-842c-915b7053d16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>7ce61859-3702-42c7-a6f6-7d9b06f517b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> My Account </value>
      <webElementGuid>c4c3eb95-b1e0-44dc-bedb-f2a90862e7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-site-wrapper&quot;)/div[@class=&quot;pre-header u-bg-primary-main_cta white align-center&quot;]/div[@class=&quot;wrap-1920 h-flex h-flex-ai-center&quot;]/div[@class=&quot;c-cta-style-extra-small customer-links uppercase hide large-show h-flex-nogrow&quot;]/a[1]</value>
      <webElementGuid>86428ae8-e61b-44be-9913-6707da01d4dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-site-wrapper']/div/div/div[3]/a</value>
      <webElementGuid>7b5ca071-03c5-463b-a2dc-36b5cbc4fb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Account')]</value>
      <webElementGuid>84908e1f-52c9-4250-b7c2-ceb86b679e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DETAILS'])[1]/following::a[1]</value>
      <webElementGuid>ffeaad3c-8691-49a5-96ff-6cf0dc621f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enjoy Complimentary Shipping'])[1]/following::a[2]</value>
      <webElementGuid>310d33df-752c-4277-a128-381b251ac053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jewelry'])[1]/preceding::a[4]</value>
      <webElementGuid>7f81ee38-320e-4255-9af2-a36667df0ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Account']/parent::*</value>
      <webElementGuid>7bc586c6-f98a-4142-8d05-73ab84aaddfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.borsheims.com/customer-account')]</value>
      <webElementGuid>ed9c7b61-6fb6-437c-a950-1866509e8c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>11cd2f6d-2081-4514-8d2f-dfcd65c098b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.borsheims.com/customer-account' and @alt = 'Account' and @title = 'Account' and (text() = ' My Account ' or . = ' My Account ')]</value>
      <webElementGuid>6d5c1911-4760-4433-baa5-89a1e9e4670d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
