<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>x-search-app-rsheims-b95</name>
   <tag></tag>
   <elementGuidId>8b18744b-8418-47fd-a208-2e120ed66432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='js-main-content']/div[2]/div/div/div[3]/x-search-app</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>x-search-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>x-search-app</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>x-search-app</value>
      <webElementGuid>b56dbd1a-b962-4a41-96d5-8abb53d5b7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>/hobo-bags</value>
      <webElementGuid>6dbe4527-4c43-46f3-a6ff-caa4101b6c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-main-content&quot;)/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;wrap-1600&quot;]/x-search-app[1]</value>
      <webElementGuid>ceff225d-4967-42a2-9fb8-8f6ee19bbee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='js-main-content']/div[2]/div/div/div[3]/x-search-app</value>
      <webElementGuid>a7d6016f-f7ea-491c-a295-c6a5df08930f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hobo International'])[2]/following::x-search-app[1]</value>
      <webElementGuid>9e9abb1e-92ef-4a89-8086-69bfee48bbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hobo International'])[1]/following::x-search-app[1]</value>
      <webElementGuid>b53be695-43a3-49c9-b26e-9e69d6a76975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google Recaptcha'])[1]/preceding::x-search-app[1]</value>
      <webElementGuid>6d256433-7305-447b-a930-fb747a2f212e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Borsheims Insider'])[1]/preceding::x-search-app[1]</value>
      <webElementGuid>44749028-20e9-4e67-90e6-67cb54099cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//x-search-app</value>
      <webElementGuid>54901b98-0398-4305-8cc0-0338521d0b31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
