<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>x-search-app-rsheims-8ec</name>
   <tag></tag>
   <elementGuidId>5841ec9a-71fc-4f9b-93df-d91a05e8b374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='js-main-content']/div[2]/div/div/div[3]/x-search-app</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>x-search-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>x-search-app</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>x-search-app</value>
      <webElementGuid>632c3eab-8b6d-41a8-9ef0-7f4728be8c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>/baccarat</value>
      <webElementGuid>603f5873-1de2-4a54-b402-5dd487afa893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-main-content&quot;)/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;wrap-1600&quot;]/x-search-app[1]</value>
      <webElementGuid>2d2d6f5b-16ec-458f-bc70-e39b8971c261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='js-main-content']/div[2]/div/div/div[3]/x-search-app</value>
      <webElementGuid>ae2a513e-8fdb-4bdf-bbed-4bbebcfd7ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baccarat Lucky Butterflies'])[1]/following::x-search-app[1]</value>
      <webElementGuid>03d2a42e-4f2a-4630-a8ae-6e2b2d19f909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baccarat Collections'])[1]/following::x-search-app[1]</value>
      <webElementGuid>f8784ce0-dfb7-4bd3-b100-b70c95560dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Borsheims Insider'])[1]/preceding::x-search-app[1]</value>
      <webElementGuid>779d02e8-cf0c-487d-801d-3c1e45ab6063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email signup'])[1]/preceding::x-search-app[1]</value>
      <webElementGuid>f572db6a-869e-4136-a043-3b462a58cd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//x-search-app</value>
      <webElementGuid>7d5090dd-b9b2-45f1-b69e-dd8d34a29403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
