<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Account</name>
   <tag></tag>
   <elementGuidId>61abc0b7-b962-40a2-9d09-bf05aa3aff33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-site-wrapper']/div/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[alt=&quot;Account&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Account&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3abbe81b-64f3-40b0-8c92-c8e14c19b304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.borsheims.com/customer-account</value>
      <webElementGuid>b21c2571-99cb-4577-b016-ca730ad00f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>49a38359-40f8-43e9-aa31-e9a3f67826bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>17570ae1-43e8-496f-9d33-8b6ac91aafa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Account </value>
      <webElementGuid>86012d75-cc10-4909-ac99-c84d45aa9903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-site-wrapper&quot;)/div[@class=&quot;pre-header u-bg-primary-main_cta white align-center&quot;]/div[@class=&quot;wrap-1920 h-flex h-flex-ai-center&quot;]/div[@class=&quot;c-cta-style-extra-small customer-links uppercase hide large-show h-flex-nogrow&quot;]/a[1]</value>
      <webElementGuid>f1980384-45c8-4b57-b250-8c3dd11bb5b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-site-wrapper']/div/div/div[3]/a</value>
      <webElementGuid>d33c1ba1-7c2f-478d-83e4-eb876df2b026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Account')]</value>
      <webElementGuid>94aaf574-691f-4af5-a618-6d660b8f0c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DETAILS'])[1]/following::a[1]</value>
      <webElementGuid>611209ca-87ce-4e5b-b6d3-ba6c11f8c041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enjoy Complimentary Shipping'])[1]/following::a[2]</value>
      <webElementGuid>f6a8b223-4824-41c8-8692-72d1120e9fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jewelry'])[1]/preceding::a[4]</value>
      <webElementGuid>3a7d4357-fbed-4623-a93e-caf2b48b1022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account']/parent::*</value>
      <webElementGuid>9f7acb66-97cf-4514-9963-835527bb8947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.borsheims.com/customer-account')]</value>
      <webElementGuid>e75e54db-54d8-4af6-85ea-6599f669e09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>6949a5c8-d19f-448e-a79c-6a3209c34760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.borsheims.com/customer-account' and @alt = 'Account' and @title = 'Account' and (text() = ' Account ' or . = ' Account ')]</value>
      <webElementGuid>2f79b0dc-2e55-483a-ac4f-aa93aad7cff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
