<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Checkout</name>
   <tag></tag>
   <elementGuidId>f1522599-a379-4369-82dc-2136b8441ee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-mini-basket-container']/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nb.round-bottom-right.button.button-block.button-medium.button-square.u-bg-primary-grey_1.u-bg-primary-grey_1--hover.u-color-secondary-white_1.uppercase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Checkout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>106c1ff7-f0e2-4ca2-aca6-7e115c4e871a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.borsheims.com/your-bag</value>
      <webElementGuid>0d3eab79-62f7-4152-b852-299b77976da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb round-bottom-right button button-block button-medium button-square u-bg-primary-grey_1 u-bg-primary-grey_1--hover u-color-secondary-white_1 uppercase</value>
      <webElementGuid>c0f473a1-4f42-45ba-9f4a-272473ca3f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checkout</value>
      <webElementGuid>3c84030a-8f05-40eb-8c41-d62e1a169a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-mini-basket-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;column np&quot;]/a[@class=&quot;nb round-bottom-right button button-block button-medium button-square u-bg-primary-grey_1 u-bg-primary-grey_1--hover u-color-secondary-white_1 uppercase&quot;]</value>
      <webElementGuid>8caa4eda-1818-47c4-8285-9357cd6acc82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-mini-basket-container']/div[2]/div/a</value>
      <webElementGuid>d7eb2403-ebb4-4c6d-be9e-e11fa0f14e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Checkout')]</value>
      <webElementGuid>11071f77-f094-46d6-9487-f9052a002a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$328.00'])[2]/following::a[1]</value>
      <webElementGuid>8e190298-0028-4d26-a8d6-6a6e824a86a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/preceding::a[1]</value>
      <webElementGuid>e8a6f0ee-1b84-4ee1-9582-3ad0309f3055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[4]/preceding::a[1]</value>
      <webElementGuid>959d3d8e-5028-4ec7-aebd-9c8295ca98f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Checkout']/parent::*</value>
      <webElementGuid>e3eab6aa-3bd5-475e-a845-d00b39de340e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.borsheims.com/your-bag')])[2]</value>
      <webElementGuid>d44cdfcc-220d-4121-9530-fdc982721770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>c25cd975-d75a-4820-902b-e445f8d60537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.borsheims.com/your-bag' and (text() = 'Checkout' or . = 'Checkout')]</value>
      <webElementGuid>729240d5-a7a5-400c-80d2-8df61f8bfc17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
