<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>4b56bdb4-c7c8-4acf-adc4-d741259cea4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='js-main-content']/div/div/div/div/div[3]/div[2]/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.button-block.headingfont.u-bg-primary-grey_1.white.uppercase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Register&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ebbcb1a4-083a-43cc-9b49-337f9c85a40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.borsheims.com/customer-create.html</value>
      <webElementGuid>66d17ea6-1198-49f7-9356-c0d712693ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>089bf88c-3d7f-406a-a50a-36c33b8a433a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>1940a7bd-10ad-4455-9627-cd5ee304144e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-block headingfont u-bg-primary-grey_1 white uppercase</value>
      <webElementGuid>0a9b3627-d47e-43b0-baf4-2c413d2e14c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>3af5b12f-81dc-4f85-86b4-c800b74bbdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-main-content&quot;)/div[@class=&quot;wrap-1600&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;column-right float-right column whole push-none large-three-fourths large-push-one-fourth large-nrp&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;row u-bg-secondary-white_1 main-content-row&quot;]/div[@class=&quot;column whole medium-five-twelfths medium-offset-one-twelfth column--newcustomer-guest&quot;]/p[@class=&quot;align-right&quot;]/a[@class=&quot;button button-block headingfont u-bg-primary-grey_1 white uppercase&quot;]</value>
      <webElementGuid>e1627a9b-eeab-42fc-b598-4ab3ccb79022</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='js-main-content']/div/div/div/div/div[3]/div[2]/p[2]/a</value>
      <webElementGuid>45a423c9-1677-42c2-9020-7315737a3d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>0448c632-a76b-4c05-8835-973f511035f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='And More...'])[1]/following::a[1]</value>
      <webElementGuid>d81af212-f96b-4082-b3c3-40d6ee5e384f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlists'])[1]/following::a[1]</value>
      <webElementGuid>3f6543bc-fb0f-411a-ade0-70c23f455d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password Lookup:'])[1]/preceding::a[1]</value>
      <webElementGuid>4c9b7f2d-2d24-49f6-9a88-4e16779e072b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='customercare@borsheims.com'])[2]/preceding::a[1]</value>
      <webElementGuid>fa0a60d2-d692-41e0-986a-5a97867f16f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>089208e6-759e-4105-aeca-07db46650a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.borsheims.com/customer-create.html')]</value>
      <webElementGuid>7e865c7b-ac08-430d-8d69-ee84e7e1481e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>69ea522a-9179-4697-99e7-635fd1ebeae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.borsheims.com/customer-create.html' and @alt = 'Register' and @title = 'Register' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>8c666b13-859d-4b21-94e9-f49565fdaf8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
