<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Checkout</name>
   <tag></tag>
   <elementGuidId>a7dac5a4-4b6e-4dd7-89b0-5d277780a282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-mini-basket-container']/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nb.round-bottom-right.button.button-block.button-medium.button-square.u-bg-primary-grey_1.u-bg-primary-grey_1--hover.u-color-secondary-white_1.uppercase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Checkout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70021ac6-cb6e-49a8-bbba-0ced2db22fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.borsheims.com/your-bag</value>
      <webElementGuid>c7325571-4c52-40e8-951b-ffab57385f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb round-bottom-right button button-block button-medium button-square u-bg-primary-grey_1 u-bg-primary-grey_1--hover u-color-secondary-white_1 uppercase</value>
      <webElementGuid>55373741-f98c-4f2f-bb27-8deb7c05e277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checkout</value>
      <webElementGuid>def9471b-9a14-4789-b742-24ce44682e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-mini-basket-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;column np&quot;]/a[@class=&quot;nb round-bottom-right button button-block button-medium button-square u-bg-primary-grey_1 u-bg-primary-grey_1--hover u-color-secondary-white_1 uppercase&quot;]</value>
      <webElementGuid>0862058b-5ecf-42d9-b678-a1515bba921d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-mini-basket-container']/div[2]/div/a</value>
      <webElementGuid>9c3d2e3a-2541-4e7c-b260-034ad251dfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Checkout')]</value>
      <webElementGuid>9e0b90d6-87ed-4f1f-9488-770c69787f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$328.00'])[2]/following::a[1]</value>
      <webElementGuid>7f8ca72a-6643-4969-9d32-ab3a455bc529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/preceding::a[1]</value>
      <webElementGuid>3486033c-7093-48d9-b987-c0fcc4fc1009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[4]/preceding::a[1]</value>
      <webElementGuid>af7c790f-a78d-4597-ae9e-a68fd4c37428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Checkout']/parent::*</value>
      <webElementGuid>fbdd6953-8c3e-4fcb-8983-dce70244b0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.borsheims.com/your-bag')])[2]</value>
      <webElementGuid>77ee920d-4820-4f07-ad5e-fc81af0a2f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>ad33b914-78ab-4f58-9d0d-1ec0e577cb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.borsheims.com/your-bag' and (text() = 'Checkout' or . = 'Checkout')]</value>
      <webElementGuid>facef9ee-2bb7-4c04-ab0f-9dee7f38dead</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
