<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>x-product-card_HOBO Sheila Crossbody, Light Grey-ims-b95-60f</name>
   <tag></tag>
   <elementGuidId>9e029a56-13fd-4e7c-b188-55868ec4ccae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//x-product-card[@name = 'HOBO Sheila Crossbody, Light Grey']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.container.is--category > div.search-container > main > div.results > x-card > x-product-card[name=&quot;HOBO Sheila Crossbody, Light Grey&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>x-product-card >> internal:has-text=&quot;HOBO Sheila Crossbody, Light Grey $278.00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>x-product-card</value>
      <webElementGuid>37ef1219-2a95-457a-8c0b-5e0cf0bb822d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>brand</name>
      <type>Main</type>
      <value>HOBO</value>
      <webElementGuid>7a2bb297-adbb-47aa-bd18-33c1d8392202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>code</name>
      <type>Main</type>
      <value>6HBAG2435</value>
      <webElementGuid>e8df1c77-3be1-4364-af49-ee1753522b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formatted-price</name>
      <type>Main</type>
      <value>$278.00</value>
      <webElementGuid>b3226f74-7fcd-40de-82aa-a4554a9506b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formatted-retail</name>
      <type>Main</type>
      <value>$278.00</value>
      <webElementGuid>54a1f83b-7108-49d6-8d10-6bfcdafddab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gtm-list</name>
      <type>Main</type>
      <value>15760339</value>
      <webElementGuid>e0cbc79a-27d7-4592-bc24-b2492faaf99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>image-url</name>
      <type>Main</type>
      <value>https://www.borsheims.com/mm5/graphics/00000001/6HBAG2435A_255x255.jpg</value>
      <webElementGuid>8a4323a4-4ac8-4cf9-ab94-c16fff42331c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HOBO Sheila Crossbody, Light Grey</value>
      <webElementGuid>efa20a70-dffc-408e-a582-b028956cc7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>price</name>
      <type>Main</type>
      <value>278</value>
      <webElementGuid>51a29ae5-bc51-48af-bd58-696a15dbb167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>retail</name>
      <type>Main</type>
      <value>278</value>
      <webElementGuid>e101a947-f0d3-480a-8403-e6823d5a839e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sale-brands</name>
      <type>Main</type>
      <value>[&quot;Alex Woo&quot;,&quot;Frederic Sage&quot;,&quot;Movado&quot;,&quot;Erika Winters&quot;,&quot;Thymes&quot;,&quot;My Story Fine Jewelry&quot;]</value>
      <webElementGuid>1a512eaf-2beb-4aed-a63c-22c1dcdd7106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>https://www.borsheims.com/hobo-sheila-crossbody-light-grey</value>
      <webElementGuid>36862d6a-9c05-418b-a965-dbdef88ace27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;container is--category&quot;]/div[@class=&quot;search-container&quot;]/main[1]/div[@class=&quot;results&quot;]/x-card[1]/x-product-card[1]</value>
      <webElementGuid>f860f282-b499-4282-a894-0f9c8559b6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Hobo Bags, Wallets, Purses  Handbags  _81ac8c/x-search-app-rsheims-b95</value>
      <webElementGuid>375a5c89-b081-4791-9039-f97e460242df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b29f9ee7-2356-4240-95b4-e54195866f5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//x-product-card[@name = 'HOBO Sheila Crossbody, Light Grey']</value>
      <webElementGuid>9d77353c-6790-4d9b-9dfe-fca56d1f157b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
