<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>x-search-app-rsheims-b95</name>
   <tag></tag>
   <elementGuidId>e02c7c95-5834-4b2c-a331-78ecc3c4c372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='js-main-content']/div[2]/div/div/div[3]/x-search-app</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>x-search-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>x-search-app</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>x-search-app</value>
      <webElementGuid>75d0931a-cd9e-4f37-ae55-b77f90a91996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>/hobo-bags</value>
      <webElementGuid>2f749608-9932-4eda-bc62-b93a8c0a391b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-main-content&quot;)/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;wrap-1600&quot;]/x-search-app[1]</value>
      <webElementGuid>4dfd8d55-3bdd-4404-9ed1-f85ae525d568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='js-main-content']/div[2]/div/div/div[3]/x-search-app</value>
      <webElementGuid>9536a78d-6d76-47a3-9890-444ea01119e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hobo International'])[2]/following::x-search-app[1]</value>
      <webElementGuid>cfd36e8a-8444-4c50-85f0-191a52b2ca40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hobo International'])[1]/following::x-search-app[1]</value>
      <webElementGuid>8065e81f-e84e-4792-86c5-8214e390af3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Borsheims Insider'])[1]/preceding::x-search-app[1]</value>
      <webElementGuid>df093e57-23be-4bd5-9b35-f06dbeb818ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email signup'])[1]/preceding::x-search-app[1]</value>
      <webElementGuid>10782412-05b3-423f-ba6c-2715514a3007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//x-search-app</value>
      <webElementGuid>6d4591c1-1204-4782-abe1-02ba526f21a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
