<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_image-container-8ec-806-b6e</name>
   <tag></tag>
   <elementGuidId>f2534e9b-7fb0-4b65-aece-9f923bdf0736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.container.image-loaded > a.top > div.image-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Vega Flute, Set of 2 image Baccarat Vega Flute, Set of 2 $490.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07932a35-9179-496b-a488-ba33aec1ec64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-container</value>
      <webElementGuid>573afabe-40b7-4ad9-87dc-4a4556a10e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;container image-loaded&quot;]/a[@class=&quot;top&quot;]/div[@class=&quot;image-container&quot;]</value>
      <webElementGuid>dce41e04-f2fc-425f-a23a-9acf8254935f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Baccarat Glassware, Stemware, Vases, F_f0aa39/x-product-card_Baccarat Vega Flute, Set of _fb1dbb</value>
      <webElementGuid>9e3ad165-3495-4271-bf64-a7e09b951a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c16444c9-6867-45e0-904f-ba0b138cbf03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>184c7dc3-ce83-4043-be3e-6abc543b7a74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
