<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>x-product-card_Baccarat Vega Flute, Set of _fb1dbb</name>
   <tag></tag>
   <elementGuidId>6be43eea-fb06-42fc-829f-0dbe0c7d2f78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//x-product-card[@name = 'Baccarat Vega Flute, Set of 2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.container.is--category > div.search-container > main > div.results > x-card > x-product-card[name=&quot;Baccarat Vega Flute, Set of 2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>x-product-card >> internal:has-text=&quot;Baccarat Vega Flute, Set of 2 $490.00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>x-product-card</value>
      <webElementGuid>6bbe1887-74c1-46ab-930d-d1b84be64d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>brand</name>
      <type>Main</type>
      <value>Baccarat</value>
      <webElementGuid>ef1d89b4-daae-458c-8237-9a004d38c8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>code</name>
      <type>Main</type>
      <value>6S0000320</value>
      <webElementGuid>8aa7e1f6-5065-4fb1-9dec-12527f75400d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formatted-price</name>
      <type>Main</type>
      <value>$490.00</value>
      <webElementGuid>1ec4da6d-2412-443e-8b39-7d91b64a0330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formatted-retail</name>
      <type>Main</type>
      <value>$490.00</value>
      <webElementGuid>e1f29337-27d5-46c2-af77-7bc9dc5f77a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gtm-list</name>
      <type>Main</type>
      <value>15760320</value>
      <webElementGuid>b1aa24e9-5e9c-40cc-80e2-55901225da84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>image-url</name>
      <type>Main</type>
      <value>https://www.borsheims.com/mm5/graphics/00000001/6S0000320A_255x255.jpg</value>
      <webElementGuid>f16859ef-fe4f-444a-ad6b-3d4b1387f239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Baccarat Vega Flute, Set of 2</value>
      <webElementGuid>77e94f72-52c4-4f15-8612-96144e115267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>price</name>
      <type>Main</type>
      <value>490</value>
      <webElementGuid>7cfc80d3-bbe1-4b7f-8382-aa881c22e909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>retail</name>
      <type>Main</type>
      <value>490</value>
      <webElementGuid>f6278a10-4458-4be3-a877-9a9cd1c2443c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sale-brands</name>
      <type>Main</type>
      <value>[&quot;Alex Woo&quot;,&quot;Frederic Sage&quot;,&quot;Movado&quot;,&quot;Erika Winters&quot;,&quot;Thymes&quot;,&quot;My Story Fine Jewelry&quot;]</value>
      <webElementGuid>88519969-d98c-4a0e-92e0-debd7448ebda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>https://www.borsheims.com/baccarat-vega-flute-set-of-2</value>
      <webElementGuid>bc8ae916-1f60-4b94-a4da-b18a0dcea156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;container is--category&quot;]/div[@class=&quot;search-container&quot;]/main[1]/div[@class=&quot;results&quot;]/x-card[1]/x-product-card[1]</value>
      <webElementGuid>716db19f-99a6-4e6e-bed4-bd5cd7a42352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Baccarat Glassware, Stemware, Vases, F_f0aa39/x-search-app-rsheims-8ec</value>
      <webElementGuid>8ce86a6d-65b3-49d3-8519-f629c870dfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>183af250-eb70-4986-aadb-a4e027725ac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//x-product-card[@name = 'Baccarat Vega Flute, Set of 2']</value>
      <webElementGuid>953e4efb-4db9-4043-ae40-b688637f5881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
