<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>x-search-app-rsheims-8ec</name>
   <tag></tag>
   <elementGuidId>097bfe71-8ece-460b-ac31-068a12d0e8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='js-main-content']/div[2]/div/div/div[3]/x-search-app</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>x-search-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>x-search-app</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>x-search-app</value>
      <webElementGuid>367467ae-a249-438c-ba13-089c15d2de5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>/baccarat</value>
      <webElementGuid>28e0ed7a-dd28-4402-ad8d-e1d681ae0586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-main-content&quot;)/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;wrap-1600&quot;]/x-search-app[1]</value>
      <webElementGuid>ce45c78f-a0b1-4f80-90e8-23a09595d408</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='js-main-content']/div[2]/div/div/div[3]/x-search-app</value>
      <webElementGuid>fe19a3d5-6246-4520-bf05-0bec91a0437d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baccarat Lucky Butterflies'])[1]/following::x-search-app[1]</value>
      <webElementGuid>a10577d8-d58e-4566-b41a-634c34221232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baccarat Collections'])[1]/following::x-search-app[1]</value>
      <webElementGuid>c3016be8-0bc5-4933-bd82-751ebde6bb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Borsheims Insider'])[1]/preceding::x-search-app[1]</value>
      <webElementGuid>2e91ea67-6b18-4265-b4f4-bd2a1ec1ee29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email signup'])[1]/preceding::x-search-app[1]</value>
      <webElementGuid>8e5c12cb-14ab-455e-a545-9a56a1b238ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//x-search-app</value>
      <webElementGuid>06c69cbf-4e66-4b4b-acda-da1d5e8133e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
