<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_hover-image image-955-08c-956</name>
   <tag></tag>
   <elementGuidId>f042e7a7-5840-46a6-bcc6-caea60f9d125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://www.borsheims.com/mm5/graphics/00000001/69/3DI005274F.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.container.has-hover-image.image-loaded > a.top > div.image-container > img.hover-image.image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Calla Diamond Bangle Bracelet in White Gold image Vhernier Calla Diamond Bangle Bracelet in White Gold $8,400.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d1c792cb-dc28-4fb7-8cab-a56844237de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f78051c-1c8b-4fa6-8445-31d6ae52ba37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>21d5d18c-f681-43c5-becb-cf22f4ce3e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> hover-image image </value>
      <webElementGuid>b3df5901-8fe7-4e92-b49b-79077c17fa82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/mm5/graphics/00000001/69/3DI005274F.jpg</value>
      <webElementGuid>a34a428f-1617-4748-b546-5b16091bd240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>1466b0eb-c176-4e19-a493-68d99fde9132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>c44f17f7-562d-42da-bd87-25f5b256168e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;container has-hover-image image-loaded&quot;]/a[@class=&quot;top&quot;]/div[@class=&quot;image-container&quot;]/img[@class=&quot;hover-image image&quot;]</value>
      <webElementGuid>98197b05-6f2c-4884-918d-55e5125a3ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Vhernier Jewelry  Borsheims/x-product-card_Vhernier Calla Diamond Bangl_1fc89a</value>
      <webElementGuid>560d8503-ef40-41d2-a1c3-39ceb268e247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f477c60d-6255-4934-8db7-a78d33b7192d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.borsheims.com/mm5/graphics/00000001/69/3DI005274F.jpg')]</value>
      <webElementGuid>f7186641-e41d-4fe9-906c-c1ab53a2f832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/mm5/graphics/00000001/69/3DI005274F.jpg']</value>
      <webElementGuid>91efcfe5-41ca-437f-915a-36775a38cce5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
