<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>x-product-card_Vhernier Calla Diamond Bangl_1fc89a</name>
   <tag></tag>
   <elementGuidId>430ee0f2-2901-4c4d-b662-3ba5715c20c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//x-product-card[@name = 'Vhernier Calla Diamond Bangle Bracelet in White Gold']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.container.is--category > div.search-container > main > div.results > x-card > x-product-card[name=&quot;Vhernier Calla Diamond Bangle Bracelet in White Gold&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>x-product-card >> internal:has-text=&quot;Vhernier Calla Diamond Bangle Bracelet in White Gold $8,400.00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>x-product-card</value>
      <webElementGuid>2a792122-1cce-4038-bfea-a6424c9c8baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>brand</name>
      <type>Main</type>
      <value>Vhernier</value>
      <webElementGuid>f86d597e-58ce-4f20-9e2c-bfd288a3d68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>code</name>
      <type>Main</type>
      <value>3DI005274</value>
      <webElementGuid>a3bb1467-590c-4db3-9852-0e7c7264fde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formatted-price</name>
      <type>Main</type>
      <value>$8,400.00</value>
      <webElementGuid>6ea21b25-718a-44ab-996b-24854db9f184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formatted-retail</name>
      <type>Main</type>
      <value>$8,400.00</value>
      <webElementGuid>08f7cb4d-eeeb-44da-947c-39369a76f44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gtm-list</name>
      <type>Main</type>
      <value>15760428</value>
      <webElementGuid>5b9626f9-13c7-4d52-bb2c-2b37bd06fecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hover-image-url</name>
      <type>Main</type>
      <value>/mm5/graphics/00000001/69/3DI005274F.jpg</value>
      <webElementGuid>9a4320b0-1be3-4080-9790-a3f5fb41694c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>image-url</name>
      <type>Main</type>
      <value>https://www.borsheims.com/mm5/graphics/00000001/69/3DI005274_255x255.jpg</value>
      <webElementGuid>1113a6ff-0e66-4cff-9b53-abf67c0d213b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Vhernier Calla Diamond Bangle Bracelet in White Gold</value>
      <webElementGuid>04c85f5e-16e2-4838-8824-34db758ee8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>price</name>
      <type>Main</type>
      <value>8400</value>
      <webElementGuid>f1873d62-d768-4058-ae0e-165bac0fa19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>retail</name>
      <type>Main</type>
      <value>8400</value>
      <webElementGuid>139e2c17-b3cb-4acd-a2c3-b69ef7e03a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sale-brands</name>
      <type>Main</type>
      <value>[&quot;Alex Woo&quot;,&quot;Frederic Sage&quot;,&quot;Movado&quot;,&quot;Erika Winters&quot;,&quot;Thymes&quot;,&quot;My Story Fine Jewelry&quot;]</value>
      <webElementGuid>7442b9ed-85ab-4fc1-912e-d2ea9150ef02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>https://www.borsheims.com/vhernier-calla-diamond-bangle-bracelet-in-white-gold-1358687</value>
      <webElementGuid>39621276-1d6d-4f76-874e-1c73d135a5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;container is--category&quot;]/div[@class=&quot;search-container&quot;]/main[1]/div[@class=&quot;results&quot;]/x-card[1]/x-product-card[1]</value>
      <webElementGuid>f5c26d65-4288-412f-be6a-255bfcd6a18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Vhernier Jewelry  Borsheims/x-search-app-rsheims-955</value>
      <webElementGuid>7bc73fe4-7d87-43ad-a8ae-467aed52ecc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>968caa90-02e3-4981-aa4c-c035a6b16531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//x-product-card[@name = 'Vhernier Calla Diamond Bangle Bracelet in White Gold']</value>
      <webElementGuid>1f9cc34b-0ae0-4d86-95b0-0e90506af870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
