<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>x-search-app-rsheims-955</name>
   <tag></tag>
   <elementGuidId>8414a0e9-de33-41d2-93b8-1ea7bee2c4c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='js-main-content']/div[2]/div/div/div[4]/x-search-app</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>x-search-app</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>x-search-app</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>x-search-app</value>
      <webElementGuid>0c187f3d-c65f-44f0-ab7b-724d4d881480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>/designers/vhernier</value>
      <webElementGuid>5d8d1f1b-8bf0-4d96-9785-3748888bcee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-main-content&quot;)/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;wrap-1600&quot;]/x-search-app[1]</value>
      <webElementGuid>b7604182-f312-4da9-b040-eec5fa49374e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='js-main-content']/div[2]/div/div/div[4]/x-search-app</value>
      <webElementGuid>46df9352-bb9a-40dd-9595-0d28653f93af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vhernier'])[2]/following::x-search-app[1]</value>
      <webElementGuid>535bc594-7dc8-4a3e-bdd8-9a8dda8076e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vhernier'])[1]/following::x-search-app[1]</value>
      <webElementGuid>71a57f4e-34c4-4997-8468-a4e533b9fd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Borsheims Insider'])[1]/preceding::x-search-app[1]</value>
      <webElementGuid>c802002c-5793-4aa4-be69-c3c6d8cda247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email signup'])[1]/preceding::x-search-app[1]</value>
      <webElementGuid>be785333-c3b3-4903-8443-299676f4ddab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//x-search-app</value>
      <webElementGuid>5e9c05d4-67f3-4548-8348-a808641fab33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
