<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Customer_VerifyPassword</name>
   <tag></tag>
   <elementGuidId>82a643fe-8828-4117-9062-5dc9a6c932bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='l-Customer_VerifyPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l-Customer_VerifyPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Confirm Password:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7661102c-f0b1-4677-8b2b-3829e852921d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d4c5050c-59d5-4b06-9883-9d5c263c0f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Customer_VerifyPassword</value>
      <webElementGuid>c1b6bc4c-310d-4220-bad5-680aed3eade5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l-Customer_VerifyPassword</value>
      <webElementGuid>7c7b827c-7e63-48b1-9f90-d6d4a2338641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34d721bb-19dd-4fb3-b624-5f0376d34157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l-Customer_VerifyPassword&quot;)</value>
      <webElementGuid>e033ec5c-9e03-4305-bac9-7de482a042db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='l-Customer_VerifyPassword']</value>
      <webElementGuid>974d57c5-700a-4838-87cd-f2bcf36a1630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='js-acad-form']/div/div/div[3]/div/input</value>
      <webElementGuid>7a528f1f-e253-474e-a98e-5ce8ae3cb9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3dc7731d-d9da-44a1-8825-033a09a464c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'Customer_VerifyPassword' and @id = 'l-Customer_VerifyPassword']</value>
      <webElementGuid>81c88476-374b-4068-a8a7-0ab6d9771b41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
