<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_Customer_ShipLastName</name>
   <tag></tag>
   <elementGuidId>cf85045d-4d89-4c6e-b678-88119bf1e253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='l-Customer_ShipLastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l-Customer_ShipLastName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Last Name:&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>881b5bc9-8282-4177-ab72-40d68d30fe2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71226c85-937b-4876-af47-41ed9eb943c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Customer_ShipLastName</value>
      <webElementGuid>f4de5b78-2538-4e85-8c93-f3d7050ede99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l-Customer_ShipLastName</value>
      <webElementGuid>52a49ada-8c65-4984-9069-3dfa9a119c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b74bdb1-2586-4a2d-8339-f2c8dfd0f81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l-Customer_ShipLastName&quot;)</value>
      <webElementGuid>2d8a83ef-353a-45a7-b428-920227edaf0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='l-Customer_ShipLastName']</value>
      <webElementGuid>4376ce33-b63c-4e07-98fe-ac19e439992b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping_fields']/div[2]/div/input</value>
      <webElementGuid>69fc1fb7-b7e2-4610-9945-c1cac09ea8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>f3b19785-1033-4ff1-aef1-9fb31efd0f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Customer_ShipLastName' and @id = 'l-Customer_ShipLastName']</value>
      <webElementGuid>7c6664d9-3a35-4e30-a513-84afea0c410e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
