<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_Customer_ShipEmail</name>
   <tag></tag>
   <elementGuidId>c49584f5-5a12-4532-84b4-aa8ef22ae0c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Customer_ShipEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Customer_ShipEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Customer_ShipEmail</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d7bf484-0998-4333-a7c1-0934c55a276f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2a89d8c3-65bf-4e41-b866-d2c7db139e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Customer_ShipEmail</value>
      <webElementGuid>df9d88d7-7fa7-4b05-8031-17ddf4416485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Customer_ShipEmail</value>
      <webElementGuid>7ba8e4e1-0377-44af-b34d-c37ecc81d413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a15c44eb-5ed3-4e1f-b063-32dd268ca2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Customer_ShipEmail&quot;)</value>
      <webElementGuid>2772ea4b-84b6-4efb-a350-a711b47d01c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Customer_ShipEmail']</value>
      <webElementGuid>a572e281-5a27-4f33-b41c-71d1b7a3f479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping_fields']/div[3]/div/input</value>
      <webElementGuid>14ddbfbf-f333-4d20-86ae-b6586a6e43fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/input</value>
      <webElementGuid>a81d2b4a-0c34-4cbd-a36c-6fbf31d32dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'Customer_ShipEmail' and @id = 'Customer_ShipEmail']</value>
      <webElementGuid>c49dfabd-2d3b-4f96-9784-5dd0f878a272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
