<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign-In Information_Customer_LoginEmail</name>
   <tag></tag>
   <elementGuidId>7cb68fc2-0bc2-4ff0-8be0-f0396f8dafc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Customer_LoginEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Customer_LoginEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Customer_LoginEmail</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23624fcf-de35-4412-b7b9-e126db638959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>706cace1-6baa-44b5-a2e8-e7060b3bdfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Customer_LoginEmail</value>
      <webElementGuid>a7bb8f60-77c3-42ff-951d-dc338454f2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Customer_LoginEmail</value>
      <webElementGuid>256a253f-cca4-4eec-bab4-cbf224150985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf533b30-04b9-4838-b981-77691e4d5479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-primary</name>
      <type>Main</type>
      <value>shipping</value>
      <webElementGuid>a7419a23-e54d-4c5b-aefa-191c9c348c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Customer_LoginEmail&quot;)</value>
      <webElementGuid>488ef3c9-4925-4a25-b68a-5f858e8201a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Customer_LoginEmail']</value>
      <webElementGuid>355f3938-aaaa-4807-9633-567970e29c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='js-acad-form']/div/div/div/div/input</value>
      <webElementGuid>35890170-2fdb-4667-b163-a3d50d239e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>6ddf14b2-75ee-4842-958c-4a5615643669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'Customer_LoginEmail' and @id = 'Customer_LoginEmail']</value>
      <webElementGuid>b8963dc9-3d2f-478e-8be8-dbb04393455c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
