<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cart (72 items)72Shopping Cart 72 items</name>
   <tag></tag>
   <elementGuidId>6fd8cbbc-f37e-4084-a64b-dfaa529a4fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gwt_minicart_div']/table/tbody/tr/td[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mini-cart-link-inactive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Shopping Cart 72 items&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12b6e8de-62bc-44d5-b551-d436008d47fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mini-cart-link-inactive</value>
      <webElementGuid>38b4eeda-2d84-474e-bd33-60aa06435506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5569a587-1491-44b1-8cd9-69ec12189957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bd9b6128-b839-42ac-b3e7-e0cb88107938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart (72 items)72Shopping Cart 72 items</value>
      <webElementGuid>8f0f9490-0df5-4b6b-8896-583d09644c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gwt_minicart_div&quot;)/table[1]/tbody[1]/tr[1]/td[2]/div[@class=&quot;mini-cart-link-inactive&quot;]</value>
      <webElementGuid>e4532bbc-7c3c-4535-b3eb-21869604568b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gwt_minicart_div']/table/tbody/tr/td[2]/div</value>
      <webElementGuid>91887e49-5961-43fe-bb39-1d471766335f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Status'])[1]/following::div[3]</value>
      <webElementGuid>9f3611d7-0b09-4746-a748-d9edadc24e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wish List'])[1]/following::div[4]</value>
      <webElementGuid>f2a1e4d5-c1ce-466f-ab14-0c548f513832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gift Registry'])[1]/preceding::div[4]</value>
      <webElementGuid>7517dfc8-c301-40dd-b3db-7604b914c6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div</value>
      <webElementGuid>0842adee-7170-4701-81f2-7ec9a941c2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cart (72 items)72Shopping Cart 72 items' or . = 'Cart (72 items)72Shopping Cart 72 items')]</value>
      <webElementGuid>5905f8f5-b54c-49b9-92c1-f4e02b04589f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
